name: CI/CD Pipeline - Data Centers Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python test_sample.py
        pytest test_sample.py -v

    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute "TP_DataCenters_GreenIT_M2_sujet correction.ipynb" --output "notebook_executed.ipynb"

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: |
          notebook_executed.ipynb
          requirements.txt
          test_sample.py
